stages:
  - test
  - build
  - deploy

run_unit_tests__python26:
  stage: test
  image: dockershelf/python:2.6
  script:
    - pip install tox
    - tox -e py26
  tags:
    - docker

run_unit_tests__python27:
  stage: test
  image: python:2.7-slim
  script:
    - pip install tox
    - tox -e py27
  tags:
    - docker

run_unit_tests__python36:
  stage: test
  image: python:3.6-slim
  script:
    - pip install tox
    - tox -e py36
  tags:
    - docker

flake8__python27:
  stage: test
  image: python:2.7-slim
  script:
    - pip install tox
    - tox -e flake8-py27
  tags:
    - docker

flake8__python36:
  stage: test
  image: python:3.6-slim
  script:
    - pip install tox
    - tox -e flake8-py36
  tags:
    - docker

build_python_package:
  stage: build
  image: python:3.6-slim
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1hr
    paths:
      - dist/
  only:
    - tags
  tags:
    - docker

upload_pypi:
  stage: deploy
  image: python:3.6-slim
  script:
    - pip install -q twine
    - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.gz
  when: manual
  only:
    - tags
  dependencies:
    - build_python_package
