stages:
  - test

run_unit_tests__python26:
  stage: test
  image: dockershelf/python:2.6
  script:
    - pip install tox
    - tox -e py26
  tags:
    - docker

run_unit_tests__python27:
  stage: test
  image: python:2.7-slim
  script:
    - pip install tox
    - tox -e py27
  tags:
    - docker

run_unit_tests__python36:
  stage: test
  image: python:3.6-slim
  script:
    - pip install tox
    - tox -e py36
  tags:
    - docker

flake8__python27:
  stage: test
  image: python:2.7-slim
  script:
    - pip install tox
    - tox -e flake8-py27
  tags:
    - docker

flake8__python36:
  stage: test
  image: python:3.6-slim
  script:
    - pip install tox
    - tox -e flake8-py36
  tags:
    - docker
