stages:
  - test
  - build
  - deploy

run_unit_tests__python36:
  stage: test
  image: python:3.6-slim
  script:
    - pip install -q tox
    - tox -e py36
  tags:
    - docker

flake8__python36:
  stage: test
  image: python:3.6-slim
  script:
    - pip install -q tox
    - tox -e flake8-py36
  tags:
    - docker

.build_rpm_template: &build_rpm_definition
  stage: build
  image: registry.umiacs.umd.edu/docker/build/umbuild:$DISTRO
  script:
    - make rpm
  artifacts:
    expire_in: 1hr
    paths:
      - dist/
#  only:
#    - tags
  tags:
    - docker

build_rpm_rhel7:
  <<: *build_rpm_definition
  variables:
    DISTRO: rhel7

build_rpm_rhel8:
  <<: *build_rpm_definition
  variables:
    DISTRO: rhel8

build_python_package:
  stage: build
  image: python:3.6-slim
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1hr
    paths:
      - dist/
#  only:
#    - tags
  tags:
    - docker

.deploy_rpm_template: &deploy_rpm_definition
  image: registry.umiacs.umd.edu/docker/build/umbuild:$DISTRO
  script:
    - make copy_rpm
    - make createrepo
  when: manual
  only:
    - tags
  tags:
    - umrepos
    - docker

deploy_rpm_rhel7:
  <<: *deploy_rpm_definition
  variables:
    DISTRO: rhel7
  dependencies:
    - build_rpm_rhel7

deploy_rpm_rhel8:
  <<: *deploy_rpm_definition
  variables:
    DISTRO: rhel8
  dependencies:
    - build_rpm_rhel8

upload_pypi:
  stage: deploy
  image: python:3.6-slim
  script:
    - pip install -q twine
    - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.gz
  when: manual
  only:
    - tags
  dependencies:
    - build_python_package
